### ISSUE TITLE
Request: Half-Level proficiency

### ISSUE THREAD

**Issue by zacdemon** [velara/pf2e-flatten#1]
As mentioned in the discord, an option for half-level proficiency would be great as a middle ground between without level and standard PF2e. 

Its following this variant : https://www.gmbinder.com/share/-MPFD4R2oaPoRvhQqfhF

So it would be rounded up.

**Comment by velara** [comment]
I've got a working prototype of this built. But, I want to do some testing before I push the changes. 

I also need to write a migration for the most recent PF2e system update, which depending on how long it takes may also delay pushing these changes. But you can expect a solution soon-ish.
