### ISSUE TITLE
In V12 can no longer right click on actors to get any context menu

### ISSUE THREAD

**Issue by Cedric-the-Destroyer** [velara/pf2e-flatten#14]
I updated to V12 and found myself unable to right click on actors directly, using Find the Culprit, if I disable this module I am able to right click on tokens again.

Actually, I see where the json was updated a few days ago, so actually probably a bug. This makes sense, as I would have sworn it was working when I first tried the update.

**Comment by velara** [comment]
Fixed in 0.6.0

**Comment by Cedric-the-Destroyer** [comment]
THANK YOU! Do you have a kofi hidden anywhere?
