### ISSUE TITLE
Flattening not reducing attack or skill bonuses anymore

### ISSUE THREAD

**Issue by Sildamet** [velara/pf2e-flatten#3]
Foundry Virtual Tabletop version 0.8.7
Pathfinder 2nd Edition version 2.4.0.6221

Flattening is still reducing saves and armor classes bonuses, but not reducing attack or skill bonuses anymore.

**Comment by velara** [comment]
Thanks for the report. I suspect its related to the some of the changes to the PF2 system made to accommodate the 0.8.x update. Unfortunately I’m not able to do any development until late July/ early August. So unless someone else submits a pull request the module won’t receive a 0.8.7 compatibility fix until then.

**Comment by Sildamet** [comment]
Appreciate your response, Velara. Sadly I'm not one of those blessed people with reasonable dev skills. So, I'll just thank you for this wonderful mod, and hope that you find time and willingness to make the adjustments. :)

**Comment by velara** [comment]
Fixed in V0.2.3
