### ISSUE TITLE
Update to Foundry V10

### ISSUE THREAD

**Issue by ReyVagabond** [velara/pf2e-flatten#5]
There is an issue when installing it to Foundry V10.x, it would be possible to fix it?

I'll be really thankful for any one with the time and knowledge to do it.

**Comment by velara** [comment]
Updating it for v10 is on my to do list now that the PF2e system is v10 ready. I’ve got no promises regarding the timeline it’ll depend a lot on how much updating is required.

**Comment by ReyVagabond** [comment]
Cool and thank you so much.

**Comment by velara** [comment]
closed in v0.4.0
